name: ccn
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - freetype=2.10.4
  - imageio=2.9.0
  - intel-openmp=2020.2
  - joblib=0.17.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.11
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.2
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - networkx=2.5
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.0.0
  - pip=21.1.2
  - pyparsing=2.4.7
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - readline=8.1
  - scikit-image=0.17.2
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.35.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip
  - pip:
    - cachetools==4.2.2
    - cellpose==0.6.5
    - cffi==1.14.5
    - chardet==4.0.0
    - google-api-core==1.30.0
    - google-auth==1.31.0
    - google-cloud-core==1.6.0
    - google-cloud-storage==1.38.0
    - google-crc32c==1.1.2
    - google-resumable-media==1.3.0
    - googleapis-common-protos==1.53.0
    - idna==2.10
    - llvmlite==0.36.0
    - natsort==7.1.1
    - numba==0.53.1
    - numpy==1.19.3
    - opencv-python-headless==4.5.2.54
    - packaging==20.9
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyqtgraph==0.12.1
    - pytz==2021.1
    - requests==2.25.1
    - rsa==4.7.2
    - scipy==1.6.3
    - tifffile==2021.6.6
    - torch==1.8.1
    - tqdm==4.61.1
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5