name: ccn
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - charls=2.2.0
  - cloudpickle=1.6.0
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.5.0
  - decorator=5.0.9
  - freetype=2.10.4
  - fsspec=0.9.0
  - giflib=5.2.1
  - icc_rt=2019.0.0
  - imagecodecs=2021.4.28
  - imageio=2.9.0
  - intel-openmp=2021.2.0
  - joblib=0.17.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libdeflate=1.7
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - matplotlib-base=3.3.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - networkx=2.5
  - ninja=1.10.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - pandas=1.1.3
  - partd=1.2.0
  - pillow=8.2.0
  - pyparsing=2.4.7
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytorch=1.8.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - scikit-image=0.18.1
  - setuptools=52.0.0
  - snappy=1.1.8
  - sqlite=3.35.4
  - tifffile=2021.4.8
  - tk=8.6.10
  - toolz=0.11.1
  - torchvision=0.9.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cachetools==4.2.2
    - cellpose==0.6.5
    - cffi==1.14.5
    - chardet==4.0.0
    - google-api-core==1.28.0
    - google-auth==1.30.1
    - google-cloud-core==1.6.0
    - google-cloud-storage==1.38.0
    - google-crc32c==1.1.2
    - google-resumable-media==1.3.0
    - googleapis-common-protos==1.53.0
    - idna==2.10
    - llvmlite==0.36.0
    - matplotlib==3.4.2
    - natsort==7.1.1
    - numba==0.53.1
    - numpy==1.19.3
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.5.2.52
    - packaging==20.9
    - pip==21.1.2
    - protobuf==3.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyqt5==5.12
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==4.19.19
    - pyqtgraph==0.12.1
    - pytz==2021.1
    - requests==2.25.1
    - rsa==4.7.2
    - scipy==1.6.3
    - six==1.16.0
    - tqdm==4.61.0
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
